CREATE DATABASE IF NOT EXISTS pdd_test CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE pdd_test;

CREATE TABLE IF NOT EXISTS results (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    score INT NOT NULL,
    total_questions INT NOT NULL DEFAULT 20,
    percent DECIMAL(5,2) NOT NULL,
    passed TINYINT(1) NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ip VARCHAR(64) NULL
);

CREATE TABLE IF NOT EXISTS question_stats (
    question_id INT PRIMARY KEY,
    wrong_count INT NOT NULL DEFAULT 0,
    total_count INT NOT NULL DEFAULT 0,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
